### ISSUE TITLE
ModuleNotFoundError: No module named 'sap'

### ISSUE THREAD

**Issue by matt1as** [jfilak/sapcli#1]
When trying to run per the README-instructions I get the following error. Do I need to "build" it somehow ( I don't know python ), or how is it supposed to find the import?
```

Mattias@Mattiass-MacBook-Pro ~/D/P/sapcli> bin/sapcli --help
Traceback (most recent call last):
  File "bin/sapcli", line 12, in <module>
    import sap
ModuleNotFoundError: No module named 'sap'
```

**Comment by jfilak** [comment]
Hmm, I need to make the binary a bit smarter. Did you run also the following?

```bash
export PYTHONPATH=$(pwd):$PYTHONPATH
```

**Comment by jfilak** [comment]
Next time I build a tool for ABAPpers, I will use Go language :) - static linking, cross compilation, fast - only I need to learn it (actually, that's a benefit - I can than apply for a job at Google then :D )

**Comment by matt1as** [comment]
I did,but i'm using Fish shell and not bash, which handles variables different,I guess it did not add pwd correctly, will try with bash tomorrow.

**Comment by matt1as** [comment]
It did indeed work when using bash and not fish as shell, and also when using the new alias you added. I will continue to try to incorporate this into our build flow.
