### ISSUE TITLE
Provide aunit results in sonar generic execution format

### ISSUE THREAD

**Issue by corani** [jfilak/sapcli#26]
To integrate the test results into Sonar, it would be great if you could provide an additional output format for sonar:

https://docs.sonarqube.org/latest/analysis/generic-test/

I had a go at it, but found the main roadblock is that this requires the full file path for each test suite. I've hacked this in using an os.walk for each test suite, assuming there are only OO testclasses. But this is obviously not a nice solution...

**Comment by jfilak** [comment]
What would be a nice solution? IMHO you can build a cache so we don't need to walk over the files for every test case but I cannot see any other feasible improvement.

**Comment by corani** [comment]
Besides building a cache only once, at the moment it's explicitly matching `clas.testclasses.abap` as those are the only unit tests I'm using. You can probably define test cases in other objects as well.

Moreover, it's currently assuming you're running the command from the root folder. Perhaps a command line flag to specify the root folder would be nice.

For the sonar generic coverage output we would need similar functionality (though matching the source files instead of the test files).

So ideally we'd have something a bit more generic.

**Comment by jfilak** [comment]
I think this issue can be solved because you added initial implementation:
https://github.com/jfilak/sapcli/blob/master/sap/cli/aunit.py#L385
