### ISSUE TITLE
SyntaxError in sapcli line 14

### ISSUE THREAD

**Issue by xtough** [jfilak/sapcli#3]
I just checked out from git and tried to run sapli but go the following error:
```
/mnt/c/SAPDevelop/sapcli$ ./sapcli --help
  File "./sapcli", line 14
    os.environ['PYTHONPATH'] = f'{base_dir}:{pythonpath}'
                                                        ^
SyntaxError: invalid syntax
```
I am using Debian on Linux subsystem for Windows.
Python 3.5.3 (and 2.7.13) are installed.
Pointing $PYTHONPATH to /usr/bin/python3 does not help.
Neither does removing Python 2.7.13.
Any ideas?

**Comment by jfilak** [comment]
You need Python>=3.6

**Comment by jfilak** [comment]
```bash
sudo echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list
sudo apt-get update
sudo apt-get install python-3.6
```
(As I've written in the issue #1 - the next tool will be in Go! :D )

**Comment by xtough** [comment]
Thanks a lot. I should have read the instructions more carefully in the first place. 
After dist-upgrade to Debian testing I could install Python 3.7.2+, which does the trick.
