### ISSUE TITLE
CI doesn't work

### ISSUE THREAD

**Issue by mnezerka** [jfilak/sapcli#54]
It seems travis stopped working for your project. The build status in README shows "all green", but this is very old status (8months). And moreover, I see the number of pylint and flake8 findings are currently not zero. It would be great to setup CI again. 

Tip: Let's you at least github actions, which are directly available from github. I'm offering my services to help you if you are interested. This task, of course, cannot be done via PR only, it requires some setup in repository settings.

**Comment by jfilak** [comment]
Thank you! I have enabled GitHub Actions and it works now.
