### ISSUE TITLE
ATC - ERROR_LEVEL is not working

### ISSUE THREAD

**Issue by lucasborin** [jfilak/sapcli#81]
Given the statement:
`./sapcli --ashost WWWW --client 001 --skip-ssl-validation --port 44300 --user XXXX --password YYYY atc run class CL_CPE_CNV_DATA_ACCESS_ADAPTER -e 1`

where `-e 1` should means: priorities higher than one are not considered

it returns the Prio 2 without respecting the `-e 1` rule: 
```
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - The Used Object is Not Visible (NVIS)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
```

**Comment by lucasborin** [comment]
Ref https://github.com/jfilak/sapcli/blob/master/doc/commands/atc.md

**Comment by jfilak** [comment]
What did you expect?

**Comment by lucasborin** [comment]
Empty result, as the object does not have any Prio 1.

**Comment by jfilak** [comment]
The paramter `-o ERROR_LEVEL` is relevand for exit code and not for printed output. The documentation says it clearly:

`Executes ATC Checks on the given object and exits with non-zero code, if ATC findings of Prio higher then the configured level are found.`

**Comment by jfilak** [comment]
Feel free to implement an option for filtering out results.
